services:
  # 1. OpenSearch 3.5.0 可能会改为2.19版本
  opensearch:
    image: opensearchproject/opensearch:3.5.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms4G -Xmx4G
      - plugins.security.disabled=true
      - node.store.allow_mmap=false
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    restart: unless-stopped
    networks:
      - aisoc-net

  # 2. OpenSearch Dashboards
  dashboards:
    image: opensearchproject/opensearch-dashboards:3.5.0
    container_name: dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    restart: unless-stopped
    networks:
      - aisoc-net

  # 3. NATS JetStream (消息总线)
  nats:
    image: nats:2.10-alpine
    container_name: nats
    command: "--jetstream --http_port 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped
    networks:
      - aisoc-net

networks:
  aisoc-net:


